### ISSUE TITLE
visualize.py zero-size array

### ISSUE THREAD

**Issue by Advaya24** [hassony2/handobjectconsist#11]
On running `python visualize.py` I get the following error (I have made sure I followed all instructions for installing the FPHAB dataset correctly):

`Traceback (most recent call last):
  File "visualize.py", line 214, in <module>
    main(args)
  File "visualize.py", line 127, in main
    crops = [vizdemo.get_crop(render_res) for render_res in render_ress]
  File "visualize.py", line 127, in <listcomp>
    crops = [vizdemo.get_crop(render_res) for render_res in render_ress]
  File "/advaya/handobjectconsist/meshreg/visualize/vizdemo.py", line 32, in get_crop
    x_min = xs.min()
  File "/h/advaya/.conda/envs/handobject_env/lib/python3.7/site-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
`

**Comment by binghui-z** [comment]
excuse me, I have encountered the same problem.， have you solved it?
