### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/chen/datasets/HO3D_v2/modelsprocess'

### ISSUE THREAD

**Issue by MengHao666** [hassony2/handobjectconsist#14]
Hi, thanks for update on ho3d_v2, I have 2 questions here:

1. When I run `python evalho3dv2.py --resume releasemodels/ho3dv2/realonly/checkpoint_200.pth --val_split test --json_folder jsonres/res`, I got error below.It seems object models are neeeded.So could u share them?
`Traceback (most recent call last):
  File "evalho3dv2.py", line 156, in <module>
    main(args)
  File "evalho3dv2.py", line 56, in main
    has_dist2strong=True,
  File "/home/chen/PycharmProjects/handobjectconsist/meshreg/netscripts/get_dataset.py", line 41, in get_dataset
    full_sequences=False,
  File "/home/chen/PycharmProjects/handobjectconsist/meshreg/datasets/ho3dv2.py", line 260, in __init__
    self.obj_meshes = ho3dfullutils.load_objects(os.path.join(self.root, "modelsprocess"))
  File "/home/chen/PycharmProjects/handobjectconsist/meshreg/datasets/ho3dfullutils.py", line 8, in load_objects
    object_names = [obj_name for obj_name in os.listdir(obj_root) if ".tgz" not in obj_name]
FileNotFoundError: [Errno 2] No such file or directory: '/home/chen/datasets/HO3D_v2/modelsprocess'
`
2. I got confuesd about that you could generate results to Codalab Competion ,as your method depicted in CVPR2020 paper couldn't handle unseen object in official evaluation set. And I remember u once upload one better result to Codalab Competition using method mentioned in your CVPR2019 paper.Could u spare some time to explain it?

Merci beaucoup!

**Comment by dihuangdh** [comment]
+1

**Comment by hassony2** [comment]
Dear @MengHao666,

Thank you for your interest in our work :) 
1. for this I used meshlab and the Quadric Edge Collapse Decimation (with texture) filter to downsample the HO3D models to reach ~2000 faces, however, I am not sure about copyright issues regarding making available the downsampled YCB models.
2. Yes, I understand how you could easily get confused with this ! 
You can find some more information about the extension of the CVPR19 work which allowed me to produce results in world coordinates [here](https://github.com/hassony2/obman_train/issues/5#issuecomment-520748759) 

Let me know if this helps !

**Comment by MengHao666** [comment]
Hi,hassony.
Thanks for reply. I get more confused after reading your reply.These are 3 questions:

1. As I can see from [Codalab Not aligned result](https://competitions.codalab.org/competitions/22485#results), you report the evaluation result on the offical evaluation set of HO3D_v2 in the following chart.  **So what is the method of this relsut? The method of your CVPR 2020 or CVPR2019 paper?**

1 | Sguha | 122 | 06/27/20 | 2.38 (1) | 0.580 (3) | 2.30 (1) | 0.565 (1) | 0.268 (2) | 0.781 (1) | View
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | jameel | 25 | 10/01/20 | 2.46 (2) | 0.631 (1) | 2.70 (2) | 0.544 (2) | 0.284 (1) | 0.760 (2) | View
3 | hpoes | 73 | 10/22/20 | 3.13 (3) | 0.587 (2) | 57.12 (10) | 0.000 (9) | 0.000 (9) | 0.000 (9) | View
4 | zly123 | 15 | 10/03/20 | 3.58 (4) | 0.379 (4) | 3.59 (3) | 0.379 (4) | 0.191 (3) | 0.643 (3) | View
5 | haomeng | 293 | 10/02/20 | 3.63 (5) | 0.370 (6) | 3.64 (4) | 0.370 (5) | 0.186 (5) | 0.631 (4) | View
6 | Harken | 10 | 09/06/20 | 4.49 (6) | 0.374 (5) | 4.36 (5) | 0.381 (3) | 0.187 (4) | 0.588 (5) | View
7 | Moyingxu | 10 | 10/04/20 | 4.88 (7) | 0.266 (8) | 57.12 (10) | 0.000 (9) | 0.000 (9) | 0.000 (9) | View
8 | yhasson | 18 | 09/14/20 | 5.52 (8) | 0.202 (9) | 5.51 (6) | 0.202 (7) | 0.106 (7) | 0.404 (7) | View





2.As I can see from [HO3D Challenge Benchmark ](https://competitions.codalab.org/competitions/22485#learn_the_details), u ever submitted a better result ,and sure, the following chart show the aligned result.And the question comes again:**What is the method of this relsut? The method of your CVPR 2020 or CVPR2019 paper?**


Method | Mesh Error (cm) (procrustes alignement) | F@5mm | F@15mm | Joint error (cm)
-- | -- | -- | -- | --
[1] | 1.06 | 0.51 | 0.94 | 3.04
[2] | 1.10 | 0.46 | 0.93 | 3.18

[1] Hampali et al. HOnnotate: A method for 3D Annotation of Hand and Object Poses. CVPR'20

[2] Hasson et al. Learning Joint Reconstruction of Hands and Manipulated Objects. CVPR'19

3.Could u share the plot data of **Figure 5**, just for the fair comparison?

Hope you could be generous to spare time to reply!
Merci beaucoup! Bonne journee!

**Comment by fuqichen1998** [comment]
I have the same question. @hassony2 Can you please directly share the ho3d results submitted to the official evaluation? Meanwhile, can you please specify which alignment you used for the metrics reported in your paper (PROCRUSTES ALIGNED or SCALE-TRANSLATION ALIGNED)?

Looking forward to your reply!
