### ISSUE TITLE
data_split_action_recognition.txt

### ISSUE THREAD

**Issue by Advaya24** [hassony2/handobjectconsist#9]
I was following the readme to run visualize.py and keep running into the following error:

`Traceback (most recent call last):
  File "visualize.py", line 214, in <module>
    main(args)
  File "visualize.py", line 51, in main
    sample_nb=None,
  File "/scratch/ssd002/home/advaya/handobjectconsist/meshreg/netscripts/get_dataset.py", line 51, in get_dataset
    split=split, use_cache=use_cache, mini_factor=mini_factor, fraction=fraction, mode=mode
  File "/scratch/ssd002/home/advaya/handobjectconsist/meshreg/datasets/fhbhands.py", line 126, in __init__
    self.load_dataset()
  File "/scratch/ssd002/home/advaya/handobjectconsist/meshreg/datasets/fhbhands.py", line 174, in load_dataset
    with open(self.info_split, "r") as annot_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/fhbhands/data_split_action_recognition.txt'
`

How do I obtain/create this file?

**Comment by hassony2** [comment]
Hi @Advaya24,

Thank you for your interest in our work.
Did you follow the [following instructions](https://github.com/hassony2/handobjectconsist#download-datasets) to download the dataset ?

Best !

Yana

**Comment by Advaya24** [comment]
Hi @hassony2,

I guess I got mislead by the expected structure given in your README. I found the file.

Thank you for the clarification! I'm really intrigued by your work.

Best,
Advaya
